---
title: "TimeSeries2"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Work with git

```{terminal, eval=FALSE}
# sync with the latest version
# run this two lines of code in terminal
git fetch upstream
git merge upstream/master
```

# Import data

```{r}
dat = read.csv("B3_HWA2.csv", stringsAsFactors = FALSE)
dat
```
```{r}
# we want 400, and leave 4 out for forecasting
datm <- dat[1:400, ] # subset 400 first rows of dat, include all columns
datf <- dat[401:404, ] # subset last 4 rows of dat, include all columns

# process 1-5
y_1 <- as.ts(datm[ , 3])
y_2 <- as.ts(datm[ , 4])
y_3 <- as.ts(datm[ , 5])
y_4 <- as.ts(datm[ , 6])
y_5 <- as.ts(datm[ , 7])

```

####################################################################

```{r}
# Plots

## Y1 - ARMA(1,1)?
layout(matrix(c(1, 1, 2,
                1, 1, 3), nrow=2, byrow=TRUE)) 
ts.plot(y_1, main = "Time Series Y1") # time series plot
acf(y_1, lag.max = 20, type = "correlation", plot = T, main = "ACF") # ACF
acf(y_1, lag.max = 20, type = "partial", plot = T, main = "PACF") # PCAF
par(mfrow = c(1,1)) # set plot window to default

## Y2 - AR(1)
layout(matrix(c(1, 1, 2,
                1, 1, 3), nrow=2, byrow=TRUE)) 
ts.plot(y_2, main = "Time Series Y2") # time series plot
acf(y_2, lag.max = 20, type = "correlation", plot = T, main = "ACF") # ACF
acf(y_2, lag.max = 20, type = "partial", plot = T, main = "PACF") # PCAF
par(mfrow = c(1,1)) # set plot window to default

## Y3 - MA(2)
layout(matrix(c(1, 1, 2,
                1, 1, 3), nrow=2, byrow=TRUE)) 
ts.plot(y_3, main = "Time Series Y3") # time series plot
acf(y_3, lag.max = 20, type = "correlation", plot = T, main = "ACF") # ACF
acf(y_3, lag.max = 20, type = "partial", plot = T, main = "PACF") # PCAF
par(mfrow = c(1,1)) # set plot window to default

## Y4 - AR(2)
layout(matrix(c(1, 1, 2,
                1, 1, 3), nrow=2, byrow=TRUE)) 
ts.plot(y_4, main = "Time Series Y4") # time series plot
acf(y_4, lag.max = 20, type = "correlation", plot = T, main = "ACF") # ACF
acf(y_4, lag.max = 20, type = "partial", plot = T, main = "PACF") # PCAF
par(mfrow = c(1,1)) # set plot window to default

## Y5 - AR(1,1)?
layout(matrix(c(1, 1, 2,
                1, 1, 3), nrow=2, byrow=TRUE)) 
ts.plot(y_5, main = "Time Series Y5") # time series plot
acf(y_5, lag.max = 20, type = "correlation", plot = T, main = "ACF") # ACF
acf(y_5, lag.max = 20, type = "partial", plot = T, main = "PACF") # PCAF
par(mfrow = c(1,1)) # set plot window to default
```


####################################################################

```{r}
## Estimation
E <- as.ts(datm$E)

## removing residuals from fitted model
### Y1
?arima
m1 <- arima(y_1, order = c(1, 0, 1))
summary(m1)
sigma21 <- m1$sigma2
E1 <- residuals(m1)

### Y2
?arima
m2 <- arima(y_2, order = c(1, 0 , 0))
summary(m2)
sigma22 <- m2$sigma2
E2 <- residuals(m2)

### Y3
?arima
m3 <- arima(y_3, order = c(0, 0 , 2))
summary(m3)
sigma23 <- m3$sigma2
E3 <- residuals(m3)

### Y4
?arima
m4 <- arima(y_4, order = c(2, 0 , 0))
summary(m4)
sigma24 <- m4$sigma2
E4 <- residuals(m4)

### Y5
?arima
m5 <- arima(y_5, order = c(1, 0 , 1))
summary(m5)
sigma25 <- m5$sigma2
E5 <- residuals(m5)

```


####################################################################

```{r}
# Splitting plots again

## Y1
layout(matrix(c(1, 1, 2,
                1, 1, 3), nrow=2, byrow=TRUE)) 
ts.plot(E1, ylab = "Residuals", col = "blue", main = "Residuals from Fitted Model Y1")
abline(a = mean(E1), b = 0) # adds horizontal line with mean(E1) as intercept and 0 slope
abline(a = mean(E1) + sigma21, b = 0, lty="dotted") # same as above + sigma2
abline(a = mean(E1) - sigma21, b = 0, lty="dotted") # same as above - sigma2

acf(E1, lag.max = 20, type = "correlation", plot = T, main = "ACF") # ACF
acf(E1, lag.max = 20, type = "partial", plot = T, main = "PACF") # PCAF
par(mfrow = c(1,1)) # set plot window to default

## Y2
layout(matrix(c(1, 1, 2,
                1, 1, 3), nrow=2, byrow=TRUE)) 
ts.plot(E2, ylab = "Residuals", col = "blue", main = "Residuals from Fitted Model Y2")
abline(a = mean(E2), b = 0) # adds horizontal line with mean(E2) as intercept and 0 slope
abline(a = mean(E2) + sigma22, b = 0, lty="dotted") # same as above + sigma2
abline(a = mean(E2) - sigma22, b = 0, lty="dotted") # same as above - sigma2

acf(E2, lag.max = 20, type = "correlation", plot = T, main = "ACF") # ACF
acf(E2, lag.max = 20, type = "partial", plot = T, main = "PACF") # PCAF
par(mfrow = c(1,1)) # set plot window to default

## Y3
layout(matrix(c(1, 1, 2,
                1, 1, 3), nrow=2, byrow=TRUE)) 
ts.plot(E3, ylab = "Residuals", col = "blue", main = "Residuals from Fitted Model Y3")
abline(a = mean(E3), b = 0) # adds horizontal line with mean(E3) as intercept and 0 slope
abline(a = mean(E3) + sigma23, b = 0, lty="dotted") # same as above + sigma2
abline(a = mean(E3) - sigma23, b = 0, lty="dotted") # same as above - sigma2

acf(E3, lag.max = 20, type = "correlation", plot = T, main = "ACF") # ACF
acf(E3, lag.max = 20, type = "partial", plot = T, main = "PACF") # PCAF
par(mfrow = c(1,1)) # set plot window to default

## Y4
layout(matrix(c(1, 1, 2,
                1, 1, 3), nrow=2, byrow=TRUE)) 
ts.plot(E4, ylab = "Residuals", col = "blue", main = "Residuals from Fitted Model Y4")
abline(a = mean(E4), b = 0) # adds horizonta2l line with mean(E4) as intercept and 0 slope
abline(a = mean(E4) + sigma24, b = 0, lty="dotted") # same as above + sigma2
abline(a = mean(E4) - sigma24, b = 0, lty="dotted") # same as above - sigma2

acf(E4, lag.max = 20, type = "correlation", plot = T, main = "ACF") # ACF
acf(E4, lag.max = 20, type = "partial", plot = T, main = "PACF") # PCAF
par(mfrow = c(1,1)) # set plot window to default

## Y5
layout(matrix(c(1, 1, 2,
                1, 1, 3), nrow=2, byrow=TRUE)) 
ts.plot(E5, ylab = "Residuals", col = "blue", main = "Residuals from Fitted Model Y5")
abline(a = mean(E5), b = 0) # adds horizontal line with mean(E5) as intercept and 0 slope
abline(a = mean(E5) + sigma25, b = 0, lty="dotted") # same as above + sigma2
abline(a = mean(E5) - sigma25, b = 0, lty="dotted") # same as above - sigma2

acf(E5, lag.max = 20, type = "correlation", plot = T, main = "ACF") # ACF
acf(E5, lag.max = 20, type = "partial", plot = T, main = "PACF") # PCAF
par(mfrow = c(1,1)) # set plot window to default
```

```{r}
### For testing auto correlations, why is t = 0 included? Not the case in 
# eviews. What does it mean? Check with Lars
e1_acf <- acf(E1, lag.max = 20, type = "correlation", plot = F) 
e2_acf <- acf(E2, lag.max = 20, type = "correlation", plot = F) 
e3_acf <- acf(E3, lag.max = 20, type = "correlation", plot = F) 
e4_acf <- acf(E4, lag.max = 20, type = "correlation", plot = F) 
e5_acf <- acf(E5, lag.max = 20, type = "correlation", plot = F) 
```


####################################################################

```{r}
### Forecasting
# use the predict function. The object parameter is the model from before
# and n.ahead gives number of time periods to forecast
y_1_pred <- predict(object = m1, n.ahead = 4)
y_2_pred <- predict(object = m2, n.ahead = 4)
y_3_pred <- predict(object = m3, n.ahead = 4)
y_4_pred <- predict(object = m4, n.ahead = 4)
y_5_pred <- predict(object = m5, n.ahead = 4)

# we can submit more than one time series to the ts.plot() function. In this case
# i add, apart from  predicted y, predicty y +- se of prediction

### Predicted Y1
ts.plot(y_1_pred$pred, y_1_pred$pred + y_1_pred$se, 
        y_1_pred$pred - y_1_pred$se, ylab = "Predicted Y", 
        main = expression(paste("Predicted ", Y['1'])), # we can use mathematical notation in r plots!
        lty=c(1:3),
        col = c("blue", "black", "black"))

### Predicted Y2
ts.plot(y_2_pred$pred, y_2_pred$pred + y_2_pred$se, 
        y_2_pred$pred - y_2_pred$se, ylab = "Predicted Y", 
        main = expression(paste("Predicted ", Y['2'])), # we can use mathematical notation in r plots!
        lty=c(1:3),
        col = c("blue", "black", "black"))

### Predicted Y3
ts.plot(y_3_pred$pred, y_3_pred$pred + y_3_pred$se, 
        y_3_pred$pred - y_3_pred$se, ylab = "Predicted Y", 
        main = expression(paste("Predicted ", Y['3'])), # we can use mathematical notation in r plots!
        lty=c(1:3),
        col = c("blue", "black", "black"))

### Predicted Y4
ts.plot(y_4_pred$pred, y_4_pred$pred + y_4_pred$se, 
        y_4_pred$pred - y_4_pred$se, ylab = "Predicted Y", 
        main = expression(paste("Predicted ", Y['4'])), # we can use mathematical notation in r plots!
        lty=c(1:3),
        col = c("blue", "black", "black"))

### Predicted Y5
ts.plot(y_5_pred$pred, y_5_pred$pred + y_5_pred$se, 
        y_5_pred$pred - y_5_pred$se, ylab = "Predicted Y", 
        main = expression(paste("Predicted ", Y['5'])), # we can use mathematical notation in r plots!
        lty=c(1:3),
        col = c("blue", "black", "black"))
```


####################################################################

```{r}
# compare fitted and actual
ts.plot(datf$Y1, y_1_pred$pred, col = c("red", "blue"))
# x & y need to be adjusted manually. A good idea is to take min(x) and add 1 as x - coordinate
# and max y remove 1 as y coordinate. Then fine tune 
legend(x = 401, y = 2, legend = c("actual", "fitted"), col = c("red", "blue"), lty=c(1,1))

### need some measurements of the forecast
y1 <- as.vector(dat$Y1[401:404]) # no real need for these to be time series objects...
y1_hat <- as.vector(y_1_pred$pred) # ... so just store them as your plain vanilla vectors :)

# RMSEA
sqrt(mean((y1-y1_hat)^2))
# MAE 
mean(abs(y1-y1_hat))
# MAPE, not exactly sure whether n = 4 or 404 in the calculations
mape <- 0
for(i in 1:4) {
  mape <- mape + abs((y1[i] - y1_hat[i])/y1[i])
}
100*mean(abs((y1-y1_hat)/y1))
```

